--local server_path = LSP_SERVERS_PATH .. "/jdtls"
--local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')

--local config = {
  --cmd = {

    --'/usr/lib/jvm/java-11-openjdk/bin/java',
    --'-Declipse.application=org.eclipse.jdt.ls.core.id1',
    --'-Dosgi.bundles.defaultStartLevel=4',
    --'-Declipse.product=org.eclipse.jdt.ls.core.product',
    --'-Dlog.protocol=true',
    --'-Dlog.level=ALL',
    --'-Xms1g',
    --'--add-modules=ALL-SYSTEM',
    --'--add-opens', 'java.base/java.util=ALL-UNNAMED',
    --'--add-opens', 'java.base/java.lang=ALL-UNNAMED',
    --'-jar', server_path .. "/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
    --'-configuration', server_path .. "/config_linux",
    --'-data', DATA_PATH .. "/java/" .. project_name
  --},
  --filetypes = {"java"},
  --root_dir = require('jdtls.setup').find_root({'pom.xml', 'settings.gradle', 'build.gradle'}),
  --settings = {
    --java = {
    --}
  --},
  --init_options = {
    --bundles = {}
  --},
--}
--
--require('jdtls').start_or_attach(config)

