alias list="pacman -Q | fzf"
alias l="lsd -l -F --size short --group-dirs first"
alias ls="ls --color"
alias t="lsd --group-dirs first --tree"
alias la="l -A"
alias lss="l --total-size"
alias npm-reset="rm node_modules package-lock.json && npm i"
alias p="echo $PWD"
alias ping="ping -c 5"
alias q="exit"
alias rm="rm -rf"
alias size="du -shc"
alias soapui="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/ && soapui"
alias sys="sudo systemctl"
alias v="nvim"
alias yarn-reset="rm node_modules yarn.lock && yarn install"
alias k="kubectl"
alias mk="minikube"
alias top="bpytop"
alias b="cd .."
alias ip="ip -c -br address show"

