alias list="dnf list --installed | fzf"
alias l="lsd -l -F --size short --group-dirs first"
alias ls="ls --color"
alias lt="lsd --group-dirs first --tree"
alias la="l -A"
alias lss="l --total-size"
alias fd="fdfind"
alias p="echo $PWD"
alias ping="ping -c 5"
alias q="exit"
alias rm="rm -rf"
alias cp="cp -rv"
alias size="du -shc"
alias sys="sudo systemctl"
alias syslog="sudo journalctl -xeu"
alias update="sudo pacman -Syu"
alias pkg="sudo nala"
alias pkgi="pkg install"
alias pkgup="pkg update"
alias pkgug="pkg upgrade"
alias pkgs="pkg search"
alias pkgh="pkg history"
alias km="keyman"
alias kml="km -l"
alias kmk="km -k"
alias v="nvim"
alias vastro="NVIM_APPNAME=AstroNvim nvim"
alias vchad="NVIM_APPNAME=NvChadChad nvim"
alias vlazy="NVIM_APPNAME=LazyVim nvim"
alias vf="fd -t file -H -E node_modules -E .git -E dist | fzf | xargs nvim"
alias g="git"
#__git_complete g __git_main
alias gc="g commit -m"
alias gcl="g clone"
alias gch="g checkout"
#__git_complete gch _git_checkout
alias gsw="g switch"
#__git_complete gsw _git_switch
alias gst="g status"
alias gps="g push"
#__git_complete gps _git_push
alias gpl="g pull"
#__git_complete gpl _git_pull
alias ga="g add"
alias gca="ga . && gc"
alias gb="g branch"
alias gl="g log --graph --oneline"
alias gla="g log --graph --all --oneline"
alias ggu="g config --get user.name"
alias gge="g config --get user.email"
alias ggr="g config --get remote.origin.url"
alias gclr='g remote prune origin && g branch | grep -v -E "(develop|master|main)" | xargs git branch -d'
alias gd="g diff --name-only"
alias gda="g diff"
#__git_complete gda _git_diff
alias grb="g rebase"
#__git_complete grb _git_rebase
alias grst="g reset"
alias gsp="g stash push -m"
alias gsl="g stash list"
alias gsa="g stash apply" #stash^{/NAME}
alias gt="g tag"
alias gtp="g push origin --tags"
alias n="npm"
alias ni="n i"
alias nr="n run"
alias nl="n ls"
alias nrs="rm node_modules package-lock.json && ni"
alias k="kubectl"
alias kg="k get"
alias kgp="kg pods"
alias kgs="kg svc"
alias kd="k delete"
alias kds="k describe"
alias kdsp="kds pod"
alias kdss="kds svc"
alias kl="k logs"
alias kcu="k config use-context"
alias kc="k config get-contexts"
alias ka="k apply -f"
alias mk="minikube"
alias top="btop"
alias topg="radeontop -c"
alias t="tmux -2"
alias ipa="ip -c -br address show"
alias code="codium"
alias docker="sudo docker"
alias d="docker"
alias ds="d start"
alias dx="d exec"
alias dr="d run"
alias db="d build"
alias dl="d ps"
alias dc="docker compose"
# alias jdk="sudo archlinux-java"
# alias update="sudo apt update -y && sudo apt upgrade -y"
alias svm="sys start libvirtd && sys start virtlogd"
alias pss="ps -auxwf"

