#Bashtop monokai theme
#by aristocratos

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#F8F8F2"

# Title color for boxes
theme[title]="#F8F8F2"

# Higlight color for keyboard shortcuts
# #F92671
theme[hi_fg]="#24C4F9"

# Background color of selected item in processes box
# #7A1137
theme[selected_bg]="#114579"

# Foreground color of selected item in processes box
theme[selected_fg]="#F8F8F2"

# Color of inactive/disabled text
theme[inactive_fg]="#595647"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
#A6E22E
theme[proc_misc]="#2CE2B5"

# Cpu box outline color
theme[cpu_box]="#75715E"

# Memory/disks box outline color
theme[mem_box]="#75715E"

# Net up/down box outline color
theme[net_box]="#75715E"

# Processes box outline color
theme[proc_box]="#75715E"

# Box divider line and small boxes line color
theme[div_line]="#595647"

# Temperature graph colors
#theme[temp_start]="#7976B7"
theme[temp_start]="#76B7B7"
#theme[temp_mid]="#D8B8B2"
#theme[temp_mid]="#A8FFFF"
#theme[temp_end]="#F92672"
theme[temp_end]="#F92672"

# CPU graph colors
#A7E22E
theme[cpu_start]="#2CE2B5"
#F8F8F2
theme[cpu_mid]="#24C4F9"
#F92672
theme[cpu_end]="#F92672"

# Mem/Disk free meter
#theme[free_start]="#75715E"
theme[free_start]="#24C4F9"
#theme[free_mid]="#a9c474"
#theme[free_end]="#e2f5bc"
theme[free_end]="#2ce25a"

# Mem/Disk cached meter
#theme[cached_start]="#75715E"
theme[cached_start]="#759990"
#theme[cached_mid]="#66D9EF"
theme[cached_mid]="#3fcfab"
#theme[cached_end]="#aae7f2"
theme[cached_end]="#2ce2b5"

# Mem/Disk available meter
#theme[available_start]="#75715E"
theme[available_start]="#759990"
#theme[available_mid]="#E6DB74"
theme[available_mid]="#3fcfab"
#theme[available_end]="#f2ecb6"
theme[available_end]="#2ce2b5"

# Mem/Disk used meter
#theme[used_start]="#75715E"
theme[used_start]="#2CE2B5"
#theme[used_mid]="#F92672"
theme[used_mid]="#24C4F9"
#theme[used_end]="#ff87b2"
theme[used_end]="#F92672"

# Download graph colors
#theme[download_start]="#2d2042"
theme[download_start]="#159d7b"
#theme[download_mid]="#7352a8"
theme[download_mid]="#2ce2b5"
#theme[download_end]="#ccaefc"
theme[download_end]="#78edd0"

# Upload graph colors
#theme[upload_start]="#570d33"
theme[upload_start]="#114579"
#theme[upload_mid]="#cf277d"
theme[upload_mid]="#1d73c9"
#theme[upload_end]="#fa91c7"
theme[upload_end]="#79b3ec"
