# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
bindkey -e
# The following lines were added by compinstall

########     My Config   ###########
# PATH
export PATH="$HOME/.local/bin:$PATH"
. "$HOME/.cargo/env"
# Imports
source $HOME/.dotfiles/aliases.sh
source $HOME/.dotfiles/env-vars.sh
source $HOME/.dotfiles/scripts/base.sh
# https://github.com/romkatv/powerlevel10k
source $HOME/.zsh/powerlevel10k/powerlevel10k.zsh-theme
# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# FZF
#source /usr/share/fzf/completion.zsh
#source /usr/share/fzf/key-bindings.zsh
# Kubectl
#source <(kubectl completion zsh)

# Completion
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit

# VI Mode
# export KEYTIMEOUT=1
# bindkey -v

# Key bindings
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "\e[3~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\ee[C" forward-word
bindkey "\ee[D" backward-word
# for rxvt
bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
# for freebsd console
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "^H" backward-delete-word
bindkey '^i' expand-or-complete-prefix
########     My Config   ###########

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# direnv
eval "$(direnv hook zsh)"

# Highlighting
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"

