#
# ~/.bashrc
#
# Default config
# If not running interactively, don't do anything
#[[ $- != *i* ]] && return
#
#alias ls='ls --color=auto'
#PS1='[\u@\h \W]\$ '

# symbols: ζ 𝝺 λ ⚡☣ ❖ ☢ ➢ ►

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Import aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# Import git utils
for file in $HOME/.gitutils/* ; do
  source $file
done

# xdg runtime dir for wsl
if [[ -z "$XDG_RUNTIME_DIR" ]]; then
  export XDG_RUNTIME_DIR=/run/user/$UID
  if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
    export XDG_RUNTIME_DIR=/tmp/$USER-runtime
    if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
      mkdir -m 0700 "$XDG_RUNTIME_DIR"
    fi
  fi
fi

# PS1="\[$(tformat lt-gray)\]\u\[$(tformat white bold)\] @ \[$(tformat gray)\]\h [\W]"
# PS1+="\[\$(git_color)\]\$(git_branch)\n"
# PS1+="\[$(tformat lt-gray)\] └─\[$(tformat yellow bold)\]λ\[$(tput sgr0)\]: "

# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[33m\]$(__git_ps1 " (%s)")\[\033[00;39m\]\$ '

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\W\[\033[33m\]$(__git_ps1 " (%s)")\[\033[01;36m\] ⚡\[\033[00;39m\]: '
export PS1

# add local bin path
export PATH="$HOME/.local/bin:$PATH"

# start ssh-agent
eval $(ssh-agent -s) > /dev/null 2>&1

# direnv hook
eval "$(direnv hook bash)"

# init nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# oracle cli
export PATH=$HOME/.local/bin/oracle-cli:$PATH
[[ -e "$HOME/.local/lib/oracle-cli/lib/python3.9/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "$HOME/.local/lib/oracle-cli/lib/python3.9/site-packages/oci_cli/bin/oci_autocomplete.sh"

# load cargo
. "$HOME/.cargo/env"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# BUN
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

